#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
curl --silent -LJO https://raw.githubusercontent.com/Diatrus/App2deb/master/Resources/App2deb > App2deb
curl --silent -LJO https://github.com/xerub/ldid/raw/master/ldid2 > ldid2
mv "$DIR/App2deb" "/usr/bin/App2deb" 
mv "$DIR/ldid2" "/usr/bin/ldid2"
chmod 0777 /usr/bin/App2deb
chmod 0777 /usr/bin/ldid2
echo "Success! App2deb can now be run anywhere!"