#!/bin/bash

# App2deb. Used to correctly and automatically create deb files of tvOS or iOS apps that can be run from /Applications.

#Check dependancies
if ! type dpkg &>/dev/null; then
	echo "Please install dpkg."
fi
if ! type ldid &>/dev/null; then
	echo "Please install ldid."
fi
if [ ! -d "$HOME/Documents/App2deb" ]; then
	mkdir "$HOME/Documents/App2deb"
fi	

#Actual script
FILENAME="$1"
if [ -z "$1" ]; then
	echo "Usage: App2deb [IPA]"
else
	if [ ! -f "$FILENAME" ]; then
		echo "File not found!"
	else
		cp "$FILENAME" "$HOME/Documents/App2deb/$FILENAME"
		cd "$HOME/Documents/App2deb"
		find . -type d -exec rm -rf '{}' \;  2> /dev/null
		echo "Extracting IPA"
		unzip -qq "$FILENAME"
		rm -rf __MACOSX
		cd Payload
		APPDIR=$(find . -type d -name "*.app") 
		cd ..
		chmod -R +x Payload
		mv Payload/"$APPDIR" "$APPDIR"
		rm -rf Payload
		rm -rf "$APPDIR"/_CodeSignature &>/dev/null
		rm -f "$APPDIR"/embedded.mobileprovision &>/dev/null
		find . -name ".DS_Store" -depth -exec rm {} \;
		echo "Getting app version..."
		VERSION=$(/usr/libexec/plistbuddy -c 'print CFBundleShortVersionString' ${APPDIR}/Info.plist)
		BUILD=$(/usr/libexec/plistbuddy -c 'print CFBundleVersion' ${APPDIR}/Info.plist)
		FIRMWARE=$(/usr/libexec/plistbuddy -c 'print MinimumOSVersion' ${APPDIR}/Info.plist)
		BUNDLEID=$(/usr/libexec/plistbuddy -c 'print CFBundleIdentifier' ${APPDIR}/Info.plist)
		NAME=$(/usr/libexec/plistbuddy -c 'print CFBundleName' ${APPDIR}/Info.plist)
		PLATFORM=$(/usr/libexec/plistbuddy -c 'print DTPlatformName' ${APPDIR}/Info.plist)
		BUNDLENAME=$(/usr/libexec/plistbuddy -c 'print CFBundleDisplayName' ${APPDIR}/Info.plist)
		echo "$VERSION"-"$BUILD"
		echo "Downloading entitlements..."
		curl --silent https://raw.githubusercontent.com/Diatrus/App2deb/master/Resources/entitlements.xml > entitlements.xml
		echo "Adding entitlements..."
		find "$APPDIR" -perm +111 -type f -not -name "*.html" -not -name "*.css" -not -name "*.js" -exec ldid -Sentitlements.xml {} &>/dev/null \;
		rm -f entitlements.xml
		echo "Packaging deb..."
		mkdir "$BUNDLEID"_"$VERSION"-"$BUILD"
		cd "$BUNDLEID"_"$VERSION"-"$BUILD"
		mkdir DEBIAN | mkdir Applications
		cd ..
		mv "$APPDIR" "$BUNDLEID"_"$VERSION"-"$BUILD"/Applications/"$APPDIR"
		cd "$BUNDLEID"_"$VERSION"-"$BUILD"
		touch DEBIAN/control
		touch DEBIAN/postinst
		read -p 'Author of Package: ' AUTHOR
		read -p 'Maintainer of Package: ' MAINTAINER
		if [ "$PLATFORM" = "appletvos" ]; then
			echo -e "Package: "$BUNDLEID"\nName: "$NAME"\nVersion: "$VERSION"-"$BUILD"\nPre-Depends: cy+cpu.arm64\nDepends: firmware (>= "$FIRMWARE"), mobilesubstrate\nSection: Applications\nPriority: Extra\nDescription: "$NAME" for the Apple TV\nAuthor: "$AUTHOR"\nMaintainer: "$MAINTAINER"\nArchitecture: appletvos-arm64\n" > DEBIAN/control
			echo -e "#!/bin/bash\necho 'finish:restart'" > DEBIAN/postinst

		elif [ "$PLATFORM" = "iphoneos" ]; then	
			echo -e "Package: "$BUNDLEID"\nName: "$NAME"\nVersion: "$VERSION"-"$BUILD"\nDepends: firmware (>= "$FIRMWARE")\nSection: Applications\nDescription: "$NAME" for iOS\nAuthor: "$AUTHOR"\nMaintainer: "$MAINTAINER"\nArchitecture: iphoneos-arm\n" > DEBIAN/control
			echo -e "#!/bin/bash\nuicache" > DEBIAN/postinst
		else
			echo "Invalid architecture!"
		fi	
		echo "Make your manual edits to the control file and press any key to continue."
		read -n 1 -s
		chmod 0755 DEBIAN/postinst
		chmod 0755 DEBIAN/control
		find . -name ".DS_Store" -depth -exec rm {} \;
		cd ..
		dpkg -b "$BUNDLEID"_"$VERSION"-"$BUILD" >/dev/null
		echo "Cleanup..."
		rm -rf "$BUNDLEID"_"$VERSION"-"$BUILD"
		rm -f "$FILENAME"
		echo "Done!"
		echo "Output: "$HOME"/Documents/App2deb/"$BUNDLEID"_"$VERSION"-"$BUILD".deb"
	fi	
fi
